name: 'Setup Node.js and pnpm'
description: 'Setup Node.js, pnpm, and install dependencies with caching'

runs:
  using: 'composite'
  steps:
    # Fixes an error related to the package manager
    # https://github.com/actions/setup-node/issues/480#issuecomment-1915448139
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: |
        # Detect which app directory we're in based on current working directory
        if [ -f "apps/frontend/pnpm-lock.yaml" ]; then
          cd apps/frontend && pnpm install --frozen-lockfile
        elif [ -f "apps/backend/pnpm-lock.yaml" ]; then
          cd apps/backend && pnpm install --frozen-lockfile
        fi
